### ISSUE TITLE
Very Good Project!

### ISSUE THREAD

**Issue by shengbinxu** [kcloze/swoole-jobs#1]
很好的几点：
1、很好的队列、消费结构，易于扩展。
2、让我学会了swoole process
3、通过信号机制，master进程对子进程进行监控。有了具体的实例，也算是加深了我对信号的理解.

但是我有一个疑问啊：
怎么调试子进程的代码？比如子进程中调用了一个undefined的函数，自然会exit()掉，会给父进程发送一个SIGCHLD信号。但是，好像没办法直接看到"function xxx undefined"这个fatal error错误。请问有什么办法？

**Comment by kcloze** [comment]
在子进程代码里面try catch，然后写日志记录，我加下这块逻辑

**Comment by kcloze** [comment]
具体可参考代码：https://github.com/kcloze/swoole-jobs/blob/master/test/jobs/MyJob.php

**Comment by xuzc** [comment]
感谢，给了我一点灵感，我也恰好想实现类似的一个jobs管理，不过需要更多的机制，例如retry、callback等😃
