### ISSUE TITLE
貌似目前问题也挺多的

### ISSUE THREAD

**Issue by leolee2356** [kcloze/swoole-jobs#11]
使用配置如下
```
return $config = [
    //log目录
    'logPath'           => __DIR__ . '/../log',
    'logSaveFileApp'    => 'application.log', //默认log存储名字
    'logSaveFileWorker' => 'crontab.log', // 进程启动相关log存储名字
    'pidPath'           => __DIR__ . '/../log',
    'sleep'             => 2, // 队列没消息时，暂停秒数
    'processName'       => ':swooleTopicQueue', // 设置进程名, 方便管理, 默认值 swooleTopicQueue
    //job任务相关
    'job'         => [
        'topics'  => [
//            ['name'=>'MyJob', 'workerMinNum'=>1, 'workerMaxNum'=>20],
//            ['name'=> 'MyJob2', 'workerMinNum'=>3, 'workerMaxNum'=>10],
//            ['name'=> 'MyJob3', 'workerMinNum'=>1, 'workerMaxNum'=>10],
            ['name'=> 'football_match_list', 'workerMinNum'=>1, 'workerMaxNum'=>10],
        ],
        // redis
        'queue'   => [
            'class'    => '\Kcloze\Jobs\Queue\RedisTopicQueue',
            'host'     => '127.0.0.1',
            'port'     => 6379,`
表现出的问题是.已经挤压了很多消息,但是主进程也已经检测到了,但是一直不处理.
记录 crontab日志如下
```
   2018/01/03 11:22:28 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:30 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:32 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:34 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:36 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:38 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:40 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:42 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:44 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:46 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:22:48 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:23:50 [info] [crontab.log] topic: football_match_list runnning len: 0
2018/01/03 11:23:52 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:23:54 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:23:56 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:23:58 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:24:00 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:24:02 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:24:04 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:24:06 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:24:08 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:24:10 [info] [crontab.log] topic: football_match_list runnning len: 24
2018/01/03 11:24:12 [info] [crontab.log] topic: football_match_list runnning len: 24

`

**Comment by kcloze** [comment]
是不是最新版呢？
看日志子进程退出了，没有再重新启动
  
![image](https://user-images.githubusercontent.com/1489176/34508869-5686fd62-f07f-11e7-8750-1f2bfa269649.png)
要有worker start的日志，先升级到最新版

**Comment by kcloze** [comment]
windows玩不来swoole，swoole基于linux
