### ISSUE TITLE
redis 驱动下的入队列和出队列分别是 lPush 和 lPop？感觉更像是栈而不是队列

### ISSUE THREAD

**Issue by aiselo** [kcloze/swoole-jobs#22]
感觉应该用 rPop 代替 lPop。
以下代码出自 Kcloze\Jobs\Queue\RedisTopicQueue
    public function push($topic, JobObject $job, $delayStrategy=1, $serializeFunc='php'): string
    {
        if (!$this->isConnected()) {
            return '';
        }

        $this->queue->lPush($topic, Serialize::serialize($job, $serializeFunc));

        return $job->uuid ?? '';
    }

    public function pop($topic, $unSerializeFunc='php')
    {
        if (!$this->isConnected()) {
            return;
        }

        $result = $this->queue->lPop($topic);

        //判断字符串是否是php序列化的字符串，目前只允许serialzie和json两种
        $unSerializeFunc=Serialize::isSerial($result) ? 'php' : 'json';

        return !empty($result) ? Serialize::unSerialize($result, $unSerializeFunc) : null;
    }

**Comment by kcloze** [comment]
可多看下文档，没错吧。
lPop 先进先出，http://www.redis.cn/commands/lpop.html
rPop 后进先出，http://www.redis.cn/commands/rpop.html

**Comment by aiselo** [comment]
文档的例子，入队列用的是 RPUSH，所以 lPop 先进先出。但 swoole-jobs 的代码中，入队列用的是 lPush，方向是相反的。
下面是我按 swoole-jobs 的方式的测试输出：
127.0.0.1:6379> lPUSH mylist "one"
(integer) 1
127.0.0.1:6379> lPUSH mylist "two"
(integer) 2
127.0.0.1:6379> lPUSH mylist "three"
(integer) 3
127.0.0.1:6379> LPOP mylist
"three"
127.0.0.1:6379> LRANGE mylist 0 -1
1) "two"
2) "one"

**Comment by kcloze** [comment]
非常感谢，redis线上我们用的少，一直没发现这个问题：lPush和rPop；rPush和lPop，应该这样成对使用。

**Comment by kcloze** [comment]
v3.0.4 已经修复
