### ISSUE TITLE
http一直提示警告是否有关系

### ISSUE THREAD

**Issue by jioswu** [kcloze/swoole-jobs#23]
Warning: Cannot modify header information - headers already sent by (output started at /mnt/hgfs/htdocs/swoole-jobs/src/Console.php:41) in /mnt/hgfs/htdocs/swoole-jobs/vendor/bramus/router/src/Bramus/Router/Router.php on line 294

**Comment by kcloze** [comment]
启动之前有输出，master分支已经修改，帮验证下

**Comment by jioswu** [comment]
`

  |  
-- | --
  | Notice: Undefined index: SCRIPT_NAME in /mnt/hgfs/htdocs/swoole-jobs/vendor/bramus/router/src/Bramus/Router/Router.php on line 427
  |  
  | Call Stack:
  | 0.2014     350872   1. {main}() /mnt/hgfs/htdocs/swoole-jobs/swoole-jobs.php:0
  | 0.2307     874240   2. Kcloze\Jobs\Console->run() /mnt/hgfs/htdocs/swoole-jobs/swoole-jobs.php:18
  | 0.2307     874240   3. Kcloze\Jobs\Console->runOpt() /mnt/hgfs/htdocs/swoole-jobs/src/Console.php:26
  | 0.2308     874264   4. Kcloze\Jobs\Console->startHttpServer() /mnt/hgfs/htdocs/swoole-jobs/src/Console.php:188
  | 0.2323     901936   5. Kcloze\Jobs\HttpServer::getInstance() /mnt/hgfs/htdocs/swoole-jobs/src/Console.php:42
  | 0.2323     902032   6. Kcloze\Jobs\HttpServer->__construct() /mnt/hgfs/htdocs/swoole-jobs/src/HttpServer.php:149
  | 0.2326     906296   7. Swoole\Http\Server->start() /mnt/hgfs/htdocs/swoole-jobs/src/HttpServer.php:83
  | 1039.6975    1232672   8. Kcloze\Jobs\HttpServer->Kcloze\Jobs\{closure}() /mnt/hgfs/htdocs/swoole-jobs/src/HttpServer.php:0
  | 1039.6977    1248160   9. Kcloze\Jobs\Router->run() /mnt/hgfs/htdocs/swoole-jobs/src/HttpServer.php:73
  | 1039.6977    1251264  10. Bramus\Router\Router->run() /mnt/hgfs/htdocs/swoole-jobs/src/Router.php:21
  | 1039.6977    1251264  11. Bramus\Router\Router->handle() /mnt/hgfs/htdocs/swoole-jobs/vendor/bramus/router/src/Bramus/Router/Router.php:286
  | 1039.6977    1251264  12. Bramus\Router\Router->getCurrentUri() /mnt/hgfs/htdocs/swoole-jobs/vendor/bramus/router/src/Bramus/Router/Router.php:336
  | 1039.6977    1251264  13. Bramus\Router\Router->getBasePath() /mnt/hgfs/htdocs/swoole-jobs/vendor/bramus/router/src/Bramus/Router/Router.php:407
  |  
  | {"code":100,"message":"ok,job has been pushed success.","content":{"topic":"MyJob","jobClass":"\\Kcloze\\Jobs\\Jobs\\MyJob","jobMethod":"test2","jobParams":["kcloze",1534736113,"oop"],"jobExtras":[],"serializeFunc":"php","uuid":"MyJob5b7a36f116d64.1534736113.0936"}}

`
警告还是一直存在
