### ISSUE TITLE
请教队列的顺序执行问题

### ISSUE THREAD

**Issue by gzanthony** [kcloze/swoole-jobs#24]
我现在的场景是这样的，下单队列->更新订单->处理K线数据->撤单，总共4个队列，配置如下
topics' => [
            // 下单
            ['name' => 'SpotMainQueue', 'workerMinNum' => 1, 'workerMaxNum' => 1, 'queueMaxNum'=> 50000],
            // 更新订单数据到 Mysql
            ['name' => 'UpdateOrder', 'workerMinNum' => 1, 'workerMaxNum' => 1, 'queueMaxNum'=> 50000],
            // 更新K线图数据
            ['name' => 'Update1MinKLine', 'workerMinNum' => 1, 'workerMaxNum' => 1, 'queueMaxNum'=> 50000],
            // 撤单队列
            ['name' => 'CancelOrder', 'workerMinNum' => 1, 'workerMaxNum' => 1, 'queueMaxNum'=> 50000]
        ],

因为我们对顺序执行有要求，所以我代码的处理流程是下单完了之后就丢给更新订单，然后再是K线，最后如果没法成交的，就丢撤单队列。

那么我现在都是给1个worker去处理，这样会不会出现抢占处理的问题？

谢谢解答.

**Comment by kcloze** [comment]
可以对job增加状态标示，目前执行方式是：有积压消息就会被消费，做不到按先后顺序，可以多从业务上面怎么避免，比如队列1执行完了再往队列2丢消息，队列2执行完了再往队列3执行消息

**Comment by gzanthony** [comment]
嗯，谢谢，目前就就是这么做的，A队列执行完了之后再丢个B队列执行.
