### ISSUE TITLE
细节问题和一点建议

### ISSUE THREAD

**Issue by dafa168** [kcloze/swoole-jobs#27]
1、启动方式，建议可以参考下 laravels、swoolefy
2、整体项目结构有点乱， 包命名规则和继承都没写上，等于摆设。（src/*，建议用app作为顶级命名空间）
3、redis加上一个选择库吧。
4、队列这块建议实现一个适配器模式，后面用mysql、redis、其它MQ都可以带入.

**Comment by dafa168** [comment]
redis有 php-redis和predis，predis扩展功能多一点，建议可以加上。

**Comment by kcloze** [comment]
已经实现了适配多种队列，最近在重构，可以参考下4.0.0分支的代码

**Comment by kcloze** [comment]
欢迎提交pr
