### ISSUE TITLE
docker安装创建镜像错误

### ISSUE THREAD

**Issue by CyberLife-Markus** [kcloze/swoole-jobs#28]
执行docker build -t swoole-jobs .之后
`Get:5 http://mirrors.aliyun.com jessie/updates/main amd64 Packages [825 kB]
Get:6 http://mirrors.aliyun.com jessie/main amd64 Packages [9098 kB]
Fetched 10.1 MB in 7s (1282 kB/s)
W: Failed to fetch http://mirrors.aliyun.com/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y         libpng-dev         libpq-dev         g++         libicu-dev         libxml2-dev         htop         git         vim         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev         zlib1g-dev         librabbitmq-dev' returned a non-zero code: 100
`

**Comment by kcloze** [comment]
应该是网络问题
