### ISSUE TITLE
集成到tp5.1,出现redis错误

### ISSUE THREAD

**Issue by BZever** [kcloze/swoole-jobs#32]
操作系统 centos7.6   
php 7.2.19  
扩展是参照tp5的项目说明集成的
一直提示 lSize() 已弃用，以下是错误日志

2019/07/24 17:52:40 YCFLOG [swoole-jobs] [error] [application.log] [PID65853] 
 错误类型：think\exception\ErrorException
错误代码：0
错误信息：Function Redis::lSize() is deprecated
错误堆栈：#0 /home/wwwroot/phpstorm/villin-task/vendor/kcloze/swoole-jobs/src/Queue/RedisTopicQueue.php(94): think\Error::appError(8192, 'Function Redis:...', '/home/wwwroot/p...', 94, Array)
#1 /home/wwwroot/phpstorm/villin-task/vendor/kcloze/swoole-jobs/src/Jobs.php(48): Kcloze\Jobs\Queue\RedisTopicQueue->len('test')
#2 /home/wwwroot/phpstorm/villin-task/vendor/kcloze/swoole-jobs/src/Process.php(138): Kcloze\Jobs\Jobs->run('test')
#3 [internal function]: Kcloze\Jobs\Process->Kcloze\Jobs\{closure}(Object(Swoole\Process))
#4 /home/wwwroot/phpstorm/villin-task/vendor/kcloze/swoole-jobs/src/Process.php(204): Swoole\Process->start()
#5 [internal function]: Kcloze\Jobs\Process->Kcloze\Jobs\{closure}(17)
#6 [internal function]: swoole_event_wait()
#7 {main}

**Comment by bzever** [comment]
解决了  redis扩展的问题，换成4.2的扩展就行了
