### ISSUE TITLE
看了源码，为什么在主进程禁用协程

### ISSUE THREAD

**Issue by Littlesqx** [kcloze/swoole-jobs#37]
https://github.com/kcloze/swoole-jobs/blob/master/src/Process.php#L440

是为了控制主进程的调度不被影响还是协程不适合消费队列？

**Comment by kcloze** [comment]
主要是因为这个
https://github.com/swoole/swoole-src/issues/2716
swoole-jobs目前定位兼容传统框架，协程不是主流，不过最新版的swoole已经允许在timer定时器主动禁用协程，后面会考虑兼容协程

**Comment by Littlesqx** [comment]
好的，感谢

**Comment by kcloze** [comment]
最新版已经兼容了协程模式
