### ISSUE TITLE
docs 裡面的 安裝 / 入門 / 開發 文件是空的

### ISSUE THREAD

**Issue by johnpupu** [kcloze/swoole-jobs#45]
docs 裡面的 安裝 / 入門 / 開發 文件是空的

**Comment by Littlesqx** [comment]
@johnpupu 我实现了一个 https://github.com/Littlesqx/aint-queue，欢迎交流

**Comment by kcloze** [comment]
看下这里:
https://github.com/kcloze/swoole-jobs/blob/master/README.zh.md
