### ISSUE TITLE
最新版本有问题

### ISSUE THREAD

**Issue by xieyuhua** [kcloze/swoole-jobs#50]
php8.0.2 + swoole4.6.2

Deprecated: Method Swoole\Timer::set() is deprecated

Warning: Undefined array key 2790123 in ****Kcloze/Jobs/Process.php on line 200

Warning: file_get_contents(***master.info): Failed to open stream: No such file or directory in ***Kcloze/Jobs/Process.php on line 417

**Comment by kcloze** [comment]
已经解决
