### ISSUE TITLE
一直出现  job execute too fast 是什么问题呢？

### ISSUE THREAD

**Issue by CloudS-Hu** [kcloze/swoole-jobs#51]
2021/05/27 11:37:26 YCFLOG [swoole-jobs] [error] [error] [PID73404] 
 job execute too fast,  uuid: MyJob60af13eae56af.1622086634.9397, execTime:4.6968460083008E-5

**Comment by kcloze** [comment]
告警信息，单个job任务执行太短，会造成进程频繁启动和退出
