### ISSUE TITLE
composer安装有问题

### ISSUE THREAD

**Issue by dimingchan** [kcloze/swoole-jobs#53]
我执行了composer require kcloze/swoole-jobs:
但是提示以下的错误：
Using version ^4.2 for kcloze/swoole-jobs
./composer.json has been updated
Running composer update kcloze/swoole-jobs
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires kcloze/swoole-jobs ^4.2 -> satisfiable by kcloze/swoole-jobs[v4.2.0].
    - kcloze/swoole-jobs v4.2.0 requires symfony/console ^3.4 -> found symfony/console[v3.4.0-BETA1, ..., 3.4.x-dev] but the package is fixed to v5.4.10 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require kcloze/swoole-jobs:*" to figure out if any version is installable, or "composer require kcloze/swoole-jobs:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

请问如何解决？

**Comment by kcloze** [comment]
版本依赖问题，最新版本已经解决
